// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReadingTracker.Library.Persistence;

#nullable disable

namespace ReadingTracker.Library.Persistence.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260920193704_AddFinishedOnAndReadingGoals")]
    partial class AddFinishedOnAndReadingGoals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("library")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReadingTracker.Library.Entries.LibraryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("BookmarkPercent")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("BookmarkReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("FinishedOn")
                        .HasColumnType("date");

                    b.Property<int?>("PageCountOverride")
                        .HasColumnType("integer");

                    b.Property<string>("ReaderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrackingMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReaderId", "BookId")
                        .IsUnique();

                    b.HasIndex("ReaderId", "FinishedOn");

                    b.ToTable("LibraryEntries", "library");
                });

            modelBuilder.Entity("ReadingTracker.Library.Entries.ReadingGoal", b =>
                {
                    b.Property<string>("ReaderId")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<int>("Books")
                        .HasColumnType("integer");

                    b.HasKey("ReaderId", "Year");

                    b.ToTable("ReadingGoals", "library");
                });

            modelBuilder.Entity("ReadingTracker.Library.Entries.ReadingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("LibraryEntryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LoggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LibraryEntryId", "OccurredAt");

                    b.ToTable("ReadingSessions", "library");
                });

            modelBuilder.Entity("ReadingTracker.Library.Entries.ReadingSession", b =>
                {
                    b.HasOne("ReadingTracker.Library.Entries.LibraryEntry", null)
                        .WithMany()
                        .HasForeignKey("LibraryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
